prgrms-fe-devcourse/FEDC3_UnsungHero_Donggeun

- src/comment/index.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 댓글을 작성하고 댓글 목록을 출력하는 기능을 구현했습니다.
close #3 
<br />
- 현재는 임시 데이터를 넣어두었고, 포스트 기능이 구현되면 포스트와 댓글 기능을 연결하려고 합니다.
- api 통신 로직은 커스텀훅으로 대체할 예정으로, 임시로 fetch를 사용하여 구현했습니다.
- 추후 컴포넌트를 분리하며 리팩토링 할 예정입니다.
> Feature/comment: 댓글 생성 및 목록 출력

- src/types/channel.ts
- src/types/comment.ts
- src/types/conversation.ts
- src/types/follow.ts
- src/types/like.ts
- src/types/message.ts
- src/types/notification.ts
- src/types/post.ts
- src/types/user.ts
- 신규 기능 추가
<br/>
> 작업한 목록
-  post, user, comment 등 모델 관련 모든 타입을 정의해두었습니다.
<br />
- API문서에 정의된 타입을 옮기다 보니 타입 정의에 오류가 있을 수 있습니다. 이런 경우 직접 수정해서 사용하시면 됩니다.
**❗types 폴더 내 모델 관련된 모든 타입을 정의해두었으니 import 하여 전역에서 사용하시면 됩니다.**
close #22
> Feature/type-definition: 모델 관련 타입 정의

- src/Router.tsx
- src/post/index.tsx
- src/search/Index.tsx
- src/search/PostListContainer.tsx
- src/search/SearchBox.tsx
- yarn.lock
- 신규 기능 추가
<br/>
> 작업한 목록
- 검색시 최신순/공감순 정렬 기능 구현(default: 최신순)
close #35 
<br />
> Feature/search: 검색시 최신순/공감순 정렬 기능 구현

- src/Router.tsx
- src/user/Pagination.tsx
- src/user/index.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 내 정보 페이지 - 내가 쓴 글 페이지네이션 구현
close #26 
<br />
> Feature/userpagination: 내가 쓴 글 페이지네이션 구현

- src/api/useMutation.ts
- src/comment/index.tsx
- src/like/index.tsx
- src/post/index.tsx
- 신규 기능 추가
- 리팩토링
- 버그 수정
<br/>
> 작업한 목록
- **좋아요를 추가, 삭제** 하는 기능을 구현했습니다.
- **useMutation 내 오류를 수정**했습니다.
상세 설명-> post, put 같은 경우 axios 함수의 2번째 인자로 data를 넣어주고, delete의 경우 config 내 data 속성을 넣어주는 것으로 분기처리 하여 현재는 잘 작동하는 것을 확인했습니다. 세 가지 메소드를 모두 하나의 훅으로 커버하려고 하니 코드가 지저분해진 것 같아 이점은 추후 리팩토링 시 개선하겠습니다.
- 댓글 컴포넌트 내 함수를 분리하였습니다.
- 구현된 기능은 아래 동영상을 참고해주세요.
<br />
- **❗useMutaion 훅 수정하였으니 반영해서 사용하시길 바랍니다! 혹시 추가적인 오류 발생 시 메신저 주세요☺️**
- close #21 
https://user-images.githubusercontent.com/60089843/211967047-83399192-f1ef-40b4-897a-d6aefc98895a.mp4
> Feature/like: 좋아요 기능 구현

- src/alarm/AlarmList.tsx
- src/alarm/AlarmListItem.tsx
- src/alarm/useProduceAlram.ts
- 신규 기능 추가
<br/>
> 작업한 목록
- 알람 리스트 렌더링
- 알람 목록 스위치 및 알람 확인
- 알람 추가 Hooks 구현
<br />
- 알람 목록의 특정 알람 목록을 클릭하면 특정 포스트로 이동하는 기능을 구현할 까 생각중이여서 서로 논의해보면 좋을 것 같습니다.
- 현재 로그인 바로 직후 알람 목록 리스트 렌더링이 되지가 않고 새로고침 후에 렌더링이 됩니다. 아마 로그인 직후에 locaStorage에 값이 설정 되기전에 data를 fetch해서 발생되는 문제인 것 같아서 이 부분도 논의해보면 좋을 것 같습니다.
- close #18
> Feature/alarm: 알람 관련 기능 구현

- src/auth/Login.tsx
- src/auth/Logout.tsx
- src/auth/SignUp.tsx
- src/contexts/TokenProvider.tsx
- src/store/contexts/TokenProvider.tsx
- src/types/auth.ts
- src/types/token.ts
- 신규 기능 추가
<br/>
> 작업한 목록
- 젼역 상태(token) 관리 기능 => 추가 및 제거
- interface 정리
- close #40 
<br />
- 충돌 발지를 위해 일단은 최상단의 App.tsx 파일에 context provider로 감싸지는 않았기에 사용해보실 분은 추가하셔야 합니다.
```
import TokenProvider from './contexts/TokenProvider';
<TokenProvider>
...
</TokenProvider>
```
- 나중에 각자 component에서 token 값을 사용하실 때 아래 소스코드를 참고하시면 됩니다!
```
import { useToken } from '../contexts/TokenProvider';  // 현재 경로에 따라 경로가 다를 수 있음
import { IToken } from '../types/token';
const tokenContextObj: IToken | null = useToken();
console.log(tokenContextObj?.token) => 해당 객체에 토큰 값 및 토근 추가, 삭제 함수가 있는데 추가 및 삭제는 auth와 관련된 기능이라 따로 소스코드는 적지 않겠습니다.
```
- Router.tsx에 router 설정을 통해 회원가입과 로그인 컴포넌트를 등록하고 layout의 Header.tsx에 로그 아웃 컴포넌트를 등록하셔서 회원가입, 로그인, 로그아웃이 정상적으로 동작되는지 확인해주시면 좋겠습니다.(localStorage 값 추가 및 삭제, …
> Feature/auth: Context API를 통한 전역 상태 관리 기능 구현

- src/Router.tsx
- src/user/Pagination.tsx
- src/user/index.tsx
- 버그 수정
<br/>
> 작업한 목록
-유저 정보 페이지 페이지네이션 total 속성 오류 수정
<br />
> 에러 수정했습니다.
> Fix/userinfo: 유저 정보페이지 페이지네이션 오류 수정

- src/auth/Login.tsx
- src/auth/SignUp.tsx
- 예외사항 check
<br/>
> 작업한 목록
- 회원 가입 실패 여부 => email, 닉네임 중복 check
- 로그인 실패 여부 => online 상태인 유저가 있는지 check
- close #51 
<br />
- 현재 로그아웃을 하더라도 GET /users/online-users 요청 시에 online 상태가 되어 있어서 다시 로그인해도 막힙니다. ⇒ 강사님
- API 수정 하신다고 하셨으니 그때 수정 하도록 하겠습니다.
- token 값 유효성 관련 작업은 context 리팩토링 시 작업 예정
> refactor/auth auth 관련 1차 리팩토링

- src/Router.tsx
- src/api/useMutation.ts
- src/contexts/TokenProvider.tsx
- 신규 기능 추가
- 스타일 속성 변경
<br/>
> 작업한 목록
- 주문하기 페이지 생성 
<br />
> refactor: 🔨 필요한 파일 수정

- src/App.tsx
- src/Router.tsx
- src/api/useMutation.ts
- src/contexts/TokenProvider.tsx
- src/layout/Header.tsx
- 버그 수정
<br/>
> 작업한 목록
<br />
- NotificationsStatus가 알림 표시 컴포넌트 입니다.(초록색 동그라미)
> refactor/all Provider 및 NotificationsStatus 컴포넌트 추가

- src/App.tsx
- src/post/CreatePost.tsx
- src/post/UpdatePost.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 글 작성중 새로고침을 눌러도 내용이 유지됨.
- 글 수정중 새로고침을 눌러도 내용이 유지됨.
#70 
<br />
App.tsx파일에 <TokenProvider>가 빠져있어서 추가했습니다.
> feat: ✨글 작성중 새로고침을 눌러도 내용이 유지됨.

- src/search/Index.tsx
- src/search/MostLikesPosts.tsx
- src/search/Pagination.tsx
- src/search/PostList.tsx
- src/search/PostListContainer.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 메인 페이지 및 각 채널 상단에 최다 공감 포스트 리스트 컴포넌트 구현
- 각 포스트 별 기본 프로필 이미지 또는 사용자 지정 프로필 이미지 노출 
close #77  
<br />
> Feature/search: 메인 페이지 및 각 채널 상단 최다 공감 포스트 리스트 구현

- src/App.tsx
- src/Router.tsx
- src/layout/Header.tsx
- src/post/CreatePost.tsx
- src/post/DetailPost.tsx
- src/post/UpdatePost.tsx
- src/post/index.tsx
- src/search/Index.tsx
- 신규 기능 추가
#71 
<br/>
> 작업한 목록
- 이제 채널을 선택하면 글쓰기 버튼이 활성화 됩니다. (안보이다가 보임)
(ui의 통일성을 위해서 disable로 해놓고 바꿀지 고민중입니다.)
- Router에 에러바운더리를 적용시켰습니다.
- Router.tsx에서 CreatePost의 params에 오타가 있어서 수정했습니다.
- 이제 '언성 히어로(로고)'를 클릭하면 메인화면으로 돌아갑니다.
- Post 컴포넌트들에 useAxios를 적용했습니다.
- 글을 수정하면 글이 있는 채널이 아닌 다른 채널에 반영되던 현상을 수정했습니다.
#
<br />
AddTempSaveOnPost PR이후 해당 브랜치를 pull 하여 작업하였습니다.
특별히 추가된 기능은 별로 없고 자잘한 수정들이 주를 이룹니다.
useAxios를 적용했습니다. 다만 UpdatePost의 경우 mutate가 정상작동하지 않아서 주석으로 처리해 두었습니다.
> Refactor/post add to channel: '채널 글 목록에 글 생성 버튼 추가하고 해당 채널에 글이 생기도록 하기' 외 몇 가지 수정사항

- src/layout/Channels.tsx
- src/layout/Header.tsx
- src/layout/index.tsx
- src/styles/globalStyle.ts
- src/styles/styled.d.ts
- src/styles/theme.ts
- 스타일 속성 변경
<br/>
> 작업한 목록
- 변경된 디자인에 맞게 레이아웃 재설정
<br />
- 채널목록은 채널 밀고나서 디자인처럼 섹션 나눌 예정입니다.
- 색깔, 폰트 크기 글로벌변수로 설정해두었습니다. Channel이나 Header 컴포넌트에서 사용예시 보실 수 있어요!
> Style/common: 전체 레이아웃 디자인 재설정

- src/App.tsx
- src/post/DetailPost.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
#79 
- DetailPost에 작성자 정보를 추가함.
- 해당 정보를 클릭 시 글 작성자 정보 페이지로 이동함.
<br />
> feat: ✨detailPost에 작성자 정보 추가.

- src/post/DetailPost.tsx
- src/post/UpdatePost.tsx
Fix: 커밋 실수로 인하여 반영사항이 취소된것 다시 반영
> Fix: 커밋 실수로 인하여 반영사항이 취소된것 다시 반영

- package.json
- src/Router.tsx
- src/auth/Header.tsx
- src/auth/Login.tsx
- src/auth/SignUp.tsx
- src/layout/index.tsx
- yarn.lock
- 스타일 속성 변경
<br/>
> 작업한 목록
- close #89 
<br />
- Header 디자인을 다른 페이지와 차이점을 두어야 해서 Router.tsx 파일과 layout > index.tsx 파일을 수정하였습니다
> Style/auth auth 관련 디자인

- src/api/Loading.tsx
- src/search/Index.tsx
- src/search/MostLikesPosts.tsx
- src/search/PostList.tsx
- src/search/PostListContainer.tsx
- src/search/SearchBox.tsx
- 리팩토링
- 스타일 속성 변경
<br/>
> 작업한 목록
- 불필요한 이미지 삭제
- px -> rem 으로 변경
- 포스트 클릭시 로그인 여부를 확인하여 로그인 유저는 특정 포스트 상세 페이지로 반대로 로그인 하지 않은 유저는 로그인 페이지로 이동하는 로직 구현
close #105 
<br />
> Feature/search: CSS 리팩토링 및 특정 포스트 클릭시 로그인 여부 확인 로직 구현

- src/common/Button.tsx
- src/common/Pagination.tsx
- src/layout/index.tsx
- src/search/MostLikesPosts.tsx
- src/search/PostList.tsx
- src/search/PostListContainer.tsx
- 리팩토링
- 스타일 속성 변경
<br/>
> 작업한 목록
- 페이지네이션 공통 컴포넌트 연결
- 채널 선택시 특정 채널의 포스트 리스트와 연결
close #109 
<br />
> Feature/search: 채널 선택시 특정 채널의 포스트 리스트와 연결 및 페이지네이션 일부 수정

- src/comment/index.tsx
- 리팩토링
<br/>
> 작업한 목록
- 불필요한 코드 삭제
<br />
> feature/search: 불필요한 코드 삭제

- src/post/DetailPost.tsx
- src/search/Index.tsx
- src/search/PostList.tsx
- src/search/PostListContainer.tsx
- 리팩토링
- 스타일 속성 변경
<br/>
> 작업한 목록
- 각 포스터에 해당하는 채널 정보 보여주기
- 글 작성하기 버튼과 최신순/공감순 스타일 적용 
close #118 
<br />
> Feature/search: 각 포스터에 해당하는 채널 정보 보여주기 및 글 작성하기 버튼 스타일 적용

- src/post/CreatePost.tsx
- src/post/UpdatePost.tsx
- 버그수정
<br/>
> 작업한 목록
#123 
- 포스트 수정 화면에서 사진이 정상적으로 출력됩니다.
<br />
> fix: 🚑포스트 수정 화면에서 이미지가 보이지 않던 문제 해결.

- src/post/DetailPost.tsx
- 버그 수정
<br/>
> 작업한 목록
#127 
fix: 🚑작성자가 아니더라도 글 수정 버튼이 보이던 문제 해결.
<br />
> fix: 🚑작성자가 아니더라도 글 수정 버튼이 보이던 문제 해결.

- src/comment/api.ts
- src/comment/index.tsx
- src/comment/tempData.ts
- src/like/api.ts
- 신규 기능 추가
<br/>
> 작업한 목록
#131
feat: ✨댓글에서 유저 아바타를 클릭시 해당 유저 정보 페이지로 이동.
<br />
필요 없는 파일인 tempDate를 제거하였습니다.
> feat: ✨댓글에서 유저 아바타를 클릭시 해당 유저 정보 페이지로 이동.

- src/search/Index.tsx
- src/search/MostLikesPosts.tsx
- src/search/PostList.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 포스트 경과시간 표시 기능 구현
close #129 
<br />
> feature/search: 포스트 경과시간 표시 기능 구현

- package.json
- src/follow/useFollow.tsx
- src/index.tsx
- src/layout/Channels.tsx
- src/notification/NotificationList.tsx
- src/notification/NotificationStatus.tsx
- src/post/DetailPost.tsx
- src/post/UpdatePost.tsx
- src/search/Index.tsx
- src/user/UserEdit.tsx
- src/user/UserEditImg.tsx
- src/user/UserFollowers.tsx
- src/user/UserFollowing.tsx
- src/user/index.tsx
- yarn.lock
* refactor: 🔨 react-query - follow
* refactor: 🔨 react-query - post
* refactor: 🔨 react-query - search
* refactor: 🔨 react-query - user
* refactor: 🔨 react-query - layout(channels)
* refactor: 🔨 react-query - notification
* refactor: 🔨 회원가입 페이지 버그
Co-authored-by: JaeKwan Ahn <52008@naver.com>
- 신규 기능 추가
- 스타일 속성 변경
<br/>
> 작업한 목록
- 주문하기 페이지 생성 
<br />
> Feature/all react-query 작업 (#135)

- src/NotFound.tsx
- src/search/PostList.tsx
- 신규 기능 추가
- 스타일 속성 변경
<br/>
> 작업한 목록
- 404Error 페이지 이미지 변경
- 메인 페이지 이동 버튼 추가
<br />
> feature/search: 404Error 페이지 이미지 변경 및 메인 페이지 이동 버튼 추가

- src/follow/useFollow.tsx
- src/post/DetailPost.tsx
- src/search/Index.tsx
- 버그수정
<br/>
> 작업한 목록
- react-query stale time 수정
<br />
> feature/all: react-query stale time 수정

- src/api/Error.tsx
- 신규 기능 추가
feat: ✨에러페이지 적용
<br/>
#
> 작업한 목록
- feat: ✨에러페이지 적용
<br />
> feat: ✨에러페이지 적용

- src/post/CreatePost.tsx
- src/post/UpdatePost.tsx
- 신규 기능 추가
<br/>
#
> 작업한 목록
- 제목을 입력하지 않을 경우 글을 작성 하거나 수정할 수 없습니다.
- 작성중인 글이 있다면 유저에게 확인하여 유저가 승낙하면 불러옵니다.
- 유저가 승낙하지 않을 경우 작성중인 내용이 모두 사라집니다.
<br />
> Fix/create post: 제목 필수 입력, 작성 중 글이 있으면 유저에게 확인 후 불러옴.

- src/notification/NotificationList.tsx
- src/notification/NotificationListItem.tsx
- src/notification/NotificationStatus.tsx
- src/post/DetailPost.tsx
- 스타일 속성 변경
- 버그 해결
<br/>
> 작업한 목록
- notificaiton 스타일
- react-query staleTime 다시 설정
<br />
> refactor/notification notification 디자인 및 버그 해결

- src/search/MostLikesPosts.tsx
- src/search/PostList.tsx
- src/search/PostListContainer.tsx
- 리팩터링
<br/>
> 작업한 목록
- 채널 리스트 표기 로직 변경.
<br />
> refactor: 🔨PostList 채널 표기 로직 변경.

- src/post/CreatePost.tsx
- src/post/DetailPost.tsx
- 신규 기능 추가
- 스타일 속성 변경
<br/>
> 작업한 목록
- 글 생성 페이지, 글 상세 페이지 줄 간격 설정
- 글 상세 페이지 height 자동 설정
<br />
> design: 💄포스트 상세 페이지 hieght 설정 및 줄간격 설정

- src/post/UpdatePost.tsx
- src/search/PostListContainer.tsx
- 신규 기능 추가
<br/>
> 작업한 목록
- 로그인 하지 않으면 글 작성불가.
- 글 삭제시 confirm
<br />
> fix: 🚑로그인 하지 않으면 글 작성불가.

- src/layout/Channels.tsx
- src/post/DetailPost.tsx
- src/search/MostLikesPosts.tsx
- src/search/PostListContainer.tsx
- 리팩터링
<br/>
> 작업한 목록
- 전체베스트, 채널간 베스트에서 테스트 채널이 표기되지 않도록함.
- 
<br />
> fix: 🔨 테스트 채널이 표기되지 않도록함.

- src/post/UpdatePost.tsx
- 버그 수정
<br/>
> 작업한 목록
- UpdatePost 화면에서 이전에 수정하려던 글의 사진이 나오던 문제 해결.
<br />
> fix: 🚑내용 수정 시 이전 글의 사진이 나오던 문제 해결.

- src/auth/Login.tsx
- src/auth/SignUp.tsx
- src/user/UserEdit.tsx
- 기능 수정
<br/>
> 작업한 목록
- 회원가입, 로그인, 유저페이지 수정 입력 정규표현식 수정
- error comment 수정
- close #153 
<br />
> reafactor/auth: 회원가입, 로그인, 유저페이지 수정 입력 정규표현식 수정
